server = false
client = true
files = [
    "googleapis/google/storage/v2/storage.proto",
    "googleapis/google/pubsub/v1/pubsub.proto",
    "googleapis/google/spanner/v1/spanner.proto",
    "googleapis/google/spanner/admin/database/v1/spanner_database_admin.proto",
    "googleapis/google/spanner/admin/instance/v1/spanner_instance_admin.proto"
]
include = [
    ["googleapis"]
]